### ISSUE TITLE
Wasm issues in parceljs and vite

### ISSUE THREAD

**Issue by knowthen** [mycelial/mycelial-js#25]
I'm working on a tutorial for v0.2.10, and I wanted to use plain JS + parcel or vite... I'm getting errors in both parceljs and vite. It seems to be wasm related.
In vite I get
```
`WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:
 TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok

Uncaught (in promise) CompileError: WebAssembly.instantiate(): BufferSource argument is empty
    at load (index.js:676:34)
    at async init (index.js:801:34)
    at async create (index.mjs:60:5)
```
In parcel I get `Failed to resolve '@mycelial/web'`
You should be able to reproduce these errors with:
```js
import { create } from '@mycelial/web';

const instance = await create('contacts');
```

**Comment by knowthen** [comment]
To reproduce in vite:
1. create vite project `npm create vite@latest`
2. replace `main.js` content with:
```js
import { create } from '@mycelial/web';

const instance = await create('contacts');
console.log(instance);
```
3. `npm run dev`
4. Check console for error

**Comment by knowthen** [comment]
To reproduce in parcel:

1. `mkdir tutorial`
2. `cd tutorial`
3. `npm init -y`
4. `npm install --save-dev parcel`
5. `npm i @mycelial/web @mycelial/v0 @mycelial/websocket`
6. create `src/index.html` with:
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
  </head>
  <body>
    <script type="module" src="index.js"></script>   
  </body>
</html>
```
7. create `src/index.js` with:
```js
import * as Mycelial from '@mycelial/web';

const instance = await Mycelial.create('contacts');
```
8. `npx parcel src/index.html`
9. Check terminal & page for errors

**Comment by lynn** [comment]
Here's a lightweight patch in the form of a Vite plugin:

```js
// vite.config.js

const wasmContentTypePlugin = {
  name: "wasm-content-type-plugin",
  configureServer(server) {
    server.middlewares.use((req, res, next) => {
      if (req.url.endsWith(".wasm")) {
        res.setHeader("Content-Type", "application/wasm");
      }
      next();
    });
  },
};

export default defineConfig({
  plugins: [wasmContentTypePlugin],
});
```

**Comment by huseeiin** [comment]
> Here's a lightweight patch in the form of a Vite plugin:
> 
> // vite.config.js
> 
> const wasmContentTypePlugin = {
>   name: "wasm-content-type-plugin",
>   configureServer(server) {
>     server.middlewares.use((req, res, next) => {
>       if (req.url.endsWith(".wasm")) {
>         res.setHeader("Content-Type", "application/wasm");
>       }
>       next();
>     });
>   },
> };
> 
> export default defineConfig({
>   plugins: [wasmContentTypePlugin],
> });

i did this but i still get the same warning in console?
